### ISSUE TITLE
How to load user profile images from a URL?

### ISSUE THREAD

**Issue by hagile** [SocialObjects-Software/SOMessaging#32]
I tried using SOMessageCell's property `userImageView` to set an image from URL into Chat, but found that its not working, when I do this its not showing up any image even I've a place holder image too. 

Please tell me is it possible or not?

P.S. setting `cell.userImage` directly is working. And I'm using `UIImageView+AFNetworking` to set image from URL into `userImageView`. 

Thanks in advance!

**Comment by shahankit** [comment]
@hagile in the configure cell method you can first set the userImageView to placeholder image of yours. In the completion block of UIImageView+AFNetworking you can set the userImageView again to the downloaded image and it will be updated and will work fine.

**Comment by hagile** [comment]
@shahankit, Hi Ankit, thank you so much for your reply. I'll try your words and will let you know here. Thanks again!

**Comment by hagile** [comment]
@shahankit , it was worked ! Sorry, I forgot to update it here. Thanks !!

**Comment by shahankit** [comment]
Not a problem man.
