### ISSUE TITLE
How to set position of cell?

### ISSUE THREAD

**Issue by shahankit** [SocialObjects-Software/SOMessaging#35]
@arturdev 
I wanted to know that how did you set the position of cell as per the fromMe parameter. Like if fromMe is YES then cell gets positioned to right, so how do you set the x co-ordinate? I saw the ballonImage and textview are all positioned at 0,0 which they take relative to cell. Correct me if I am wrong.
I want this because I want to have a new cell which is centered unlike right or left.

**Comment by arturdev** [comment]
See https://github.com/SocialObjects-Software/SOMessaging/blob/master/SOMessaging/SOMessageCell.m#L314

**Comment by shahankit** [comment]
Thanks
