### ISSUE TITLE
why pan gesture recognizer in SOMessageInputView?

### ISSUE THREAD

**Issue by jpmhouston** [SocialObjects-Software/SOMessaging#41]
Is the `UIPanGestureRecognizer` in `SOMessageInputView` only for the behavior where the input view bar ducks down as the user drags the scrollview?

I'm using the `SOMessageInputView` without the rest of `SOMessaging` (works pretty well, thanks!) and wanting to omit that behavior. I'll make a pull request at some point that makes it an option, probably just a BOOL property in SOMessageInputView.h.

Would you like, in my pull request, to expose that option in `SOMessagingDataSource` also? What should this be called, something like "shouldRetractInputViewOnDrag", "dragCanDuckInputBar"?

Note: those settings methods might be better suited for the Delegate protocol instead, that is, if following Cocoa's usual data source / delegate division of labor.

**Comment by arturdev** [comment]
Yes. Call it `@property (nonatomic) BOOL hideKeyboardOnDrag;`

**Comment by jpmhouston** [comment]
Does this gesture recognizer hide the keyboard as well as the input view? Ok.
BTW, my project was suspended and I might never actually get around to do this. Closing this issue.
