### ISSUE TITLE
How to add image to Textview?

### ISSUE THREAD

**Issue by bintu1234** [SocialObjects-Software/SOMessaging#47]
HI How to add border to text view i tried with textview methods like below
 self.textView.layer.borderColor=[UIColor redColor].CGColor;
and also tried with the image like below 
self.textView.backgroundColor=[UIColor colorWithPatternImage:[UIImage imageNamed:@"separator.png"]];
 but it is not showing any modifications. can any body please help me how to add border to text view
like below
 
![textview](https://cloud.githubusercontent.com/assets/15229187/14280072/177d9f54-fb4e-11e5-9012-b677fdb3d442.png)

**Comment by WarisSaqi** [comment]
@bintu1234 , sorry for late reply i am little busy.
Go into **SOMessageInputView.m** then there is a method named **adjustInputView** and add these lines in the end of the method

```self.textBgImageView.layer.cornerRadius = 5.0;
    self.textBgImageView.layer.masksToBounds = YES;
    self.textBgImageView.layer.borderColor = [UIColor grayColor].CGColor;
    self.textBgImageView.layer.borderWidth = 2.0;
    self.textBgImageView.layer.masksToBounds = YES;```

**Comment by bintu1234** [comment]
@WarisSaqi  Thank you very much.

**Comment by bintu1234** [comment]
@WarisSaqi  if you don't mine please check this #48  issue also if you have enough time. I tried my level best for that but getting errors.

**Comment by WarisSaqi** [comment]
Kindly close this close
