### ISSUE TITLE
How can I use FetchedResultsController with it?

### ISSUE THREAD

**Issue by nasserprofessional** [SocialObjects-Software/SOMessaging#6]
I am having problems using this with core data fetchedResultsController would be great if you could help me out.

The problem is that the It needs an NSArray of SOMessage objects. I dont like the idea of converting fetchedResultsController to NSArray because I think when I try to reload new message obviously it will have to convert each time and if the array already has data it will crash. Any Ideas?

**Comment by zeeshanhaider-devbatch** [comment]
@nasserprofessional How have you implemented CoreData Fetched Result Controller on it?
