### ISSUE TITLE
[_UIAlertShimPresentingViewController my_shouldAutorotate]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by cooler333** [SocialObjects-Software/SOMessaging#7]
when i init UIAlertView Xcode throw the exception

**Comment by hagile** [comment]
**Caution** : Please back up your code before performing these steps. Also, not recommended if you're using pod.

**Steps:**
**1. Remove this files**

UINavigationController+Rotation.h
UINavigationController+Rotation.m

**2. Open SOMessageInputView.m**

>remove this line, 

    #import "UINavigationController+Rotation.h"

> remove all occurrences of these lines,

    UINavigationController *nc = [self navigationControllerInstance];
    nc.cantAutorotate = NO;

**3. You're done!**

Now it won't crash your app and still you can use SOMessaging in all supported orientations too.

<hr>

Note for @arturdev , please provide some mechanism so that it'll helpful to everyone who're using this as pod file. Thanks!

**Comment by hagile** [comment]
I've fork the project and remove UINavigationController+Rotation dependancy, you can check it out here. https://github.com/hagile/SOMessaging

**Comment by Niraj91** [comment]
thanks

On Sat, Mar 21, 2015 at 4:26 PM, Hemang Agile <notifications@github.com>
wrote:

> I've fork the project and remove UINavigationController+Rotation
> dependancy, you can check it out here.
> https://github.com/hagile/SOMessaging
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SocialObjects-Software/SOMessaging/issues/7#issuecomment-84310340>
> .
>



-- 
-- 
Regards
*Niraj Gambhava*
iOS Developer
Call: +91 8866 122393
Skype: gambhavaniraj.si <gambhavaniraj.si@gmail.com>

**Comment by hirenpanchal1608** [comment]
Do whatever you want to do after finishing the animation of alertview dismiss OR Actionsheet dismiss.

**Comment by RajChanchal** [comment]
I am using POD and I am facing the same issue with latest Pod I installed.. I cann't do above changes though. Any suggestion?

**Comment by Niraj91** [comment]
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Niraj has been waiting for you to confirm your trusted relationship:

Confirm &#9658;

This is your final reminder.
Not sure you know Niraj?

View their photos to see if you recognize them, reject their invitation (and block reminders from them) or simply ignore this email.

*This offer has been sent by patelniraj2017@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.
